# This template/config file is meant for local developer overrides only, at high priority.
# Only the template should live in Git and be updated over time with handy developer options.
# It is safe to hard code secrets here for easier testing, but consider using the .env file

organization:
  # This would override the same config option set in the client file, comment to let it win
  name: Adaptavist Dev

# Note that having this section in the local config file will block any other config file to contribute catalog items
catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location]
  locations:
    # Local example data, file locations are relative to the backend process, typically `packages/backend`
    - type: file
      target: ../../examples/entities.yaml

    # Local example template
    - type: file
      target: ../../examples/template/template.yaml
      rules:
        - allow: [Template]

    # Local example organizational data
    - type: file
      target: ../../examples/org.yaml
      rules:
        - allow: [User, Group]