apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: An example of a Backstage application.
  # Example for optional annotations
  annotations:
    jira/project-key: VSH
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
